name: Bug Report
title: "[BUG] "
description: Report a bug related to this project
labels: ["bug"]
body:

  - type: input
    id: nodejs-version
    attributes:
      label: Node.js Version
      description: Enter the version of Node.js you are using.
      placeholder: 24.21.0
    validations:
      required: true

  - type: input
    id: whatsapp-version
    attributes:
      label: WhatsApp Version
      description: Enter the version of WhatsApp you are using.
      placeholder: WhatsApp Business 2.26.7.73 (Android 16)
    validations:
      required: true

  - type: textarea
    id: socket-configuration
    attributes:
      label: Socket Configuration
      description: |
        Describe the socket configuration used by your Zapo instance.
      placeholder: new WaClient({ ... })
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: |
        Describe the issue you're facing, including what you were trying to do and what happened.
        You may attach relevant logs or screenshots if needed.
      placeholder: |
        What were you trying to do?
        What happened?
        Include relevant logs or screenshots if possible.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest commit of this project.
          required: true
        - label: I have checked the documentation and found no answer.
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate.
          required: true
        - label: I am using the latest version of WhatsApp.
        - label: I have provided sufficient information.
          required: true
